kubernetes-sigs/apiserver-builder-alpha

- pkg/cmd/server/start.go
> Change order of applying server config to ensure authentication config is correctly applied

- README.md
- cmd/apiserver-boot/boot/glide.go
- docs/concepts/auth.md
- example/Makefile
- pkg/cmd/server/start.go
- pkg/test/ginkgo.go
- pkg/test/server.go
Reading the docs and fixing them up as I go. Trying to create a project with `apiserver-boot` and bumped into [an issue](https://github.com/kubernetes-incubator/apiserver-builder/pull/51/commits/236b7ec77b592a99526766f2f6866be617665b53) with that, which I've documented in the code.
@pwittrock
> Learning the repo, work through docs, minor refactoring

- cmd/apiserver-boot/boot/build.go
- cmd/apiserver-boot/boot/build_container.go
- cmd/apiserver-boot/boot/create_resource_group.go
- cmd/apiserver-boot/boot/create_resource_version.go
- cmd/apiserver-boot/boot/generate.go
- cmd/apiserver-boot/boot/glide.go
- cmd/apiserver-boot/main.go
- docs/adding_subresources.md
- docs/adding_validation.md
- Add a command for creating a container to apiserver-boot
- Update document for adding validation logic to a resource
- Fixup descriptions of apiserver-boot commands
> Add apiserver-boot create-container command + fixups

- cmd/apiregister-gen/generators/unversioned_generator.go
Signed-off-by: Andrei Vagin <avagin@virtuozzo.com>
> Return Spec form GetSpec

- cmd/apiregister-gen/generators/apis_generator.go
- cmd/apiregister-gen/generators/parser.go
- cmd/apiregister-gen/generators/util.go
- cmd/apiserver-boot/boot/create_resource.go
- cmd/apiserver-boot/boot/util.go
- example/.gitignore
- example/Makefile
- example/pkg/apis/kingsport/doc.go
- example/pkg/apis/kingsport/install/doc.go
- example/pkg/apis/kingsport/v1/doc.go
- example/pkg/apis/kingsport/v1/festival_types.go
- example/pkg/apis/kingsport/v1/festival_types_test.go
- example/pkg/apis/kingsport/v1/v1_suite_test.go
- example/pkg/controller/festival/controller.go
- example/pkg/controller/festival/controller_test.go
- example/pkg/controller/festival/festival_suite_test.go
- pkg/builders/api_group_builder.go
> Add support for non-namespaced kinds

- cmd/apiserver-boot/boot/glide.go
- cmd/apiserver-builder-release/main.go
Build release bin in working directory instead of tmp directory
> Package vendored deps as tar in release package

- docs/adding_custom_rest.md
TODO: revert this commit when #92 is fixed.
> docs: mention temporary workaround for #92

- docs/concepts/aggregation.md
Reading through the docs I came across a few small things I thought I'd fix
> docs: Small fixes to aggregation concepts

- cmd/apiserver-boot/boot/create/create.go
- cmd/apiserver-boot/boot/create/resource.go
- cmd/apiserver-boot/boot/create/subresource.go
- cmd/apiserver-boot/boot/create/util.go
- example/pkg/apis/miskatonic/v1beta1/scale_university_types.go
- example/pkg/apis/miskatonic/v1beta1/scale_university_types_test.go
- example/pkg/apis/miskatonic/v1beta1/university_types.go
Code could be refactored to be more clean, but it works for now :)
> Add support to apiserver-boot for generating subresources + tests

- cmd/apiserver-boot/boot/init_repo/glide.go
fix: https://github.com/kubernetes-incubator/apiserver-builder/issues/145
> use a version retrieve function.

- cmd/apiregister-gen/generators/controller_generator.go
- cmd/apiserver-boot/boot/build/build_container.go
- cmd/apiserver-boot/boot/build/build_resource_config.go
- cmd/apiserver-boot/boot/build/docs.go
- cmd/apiserver-boot/boot/create/resource.go
- cmd/apiserver-boot/boot/init_repo/glide.go
- cmd/apiserver-boot/boot/init_repo/repo.go
- cmd/apiserver-boot/boot/run/local.go
- cmd/apiserver-boot/boot/run/local_aggregated.go
- cmd/apiserver-boot/boot/run/run.go
- cmd/apiserver-boot/boot/util/util.go
- cmd/apiserver-boot/main.go
- pkg/cmd/server/start.go
- pkg/controller/controller.go
- support for running with minikube
- replace execs
> Various improvements

- docs/concepts/api_building_overview.md
I was stuck for hours because I didn't update to the storage. I hope this clarification helps others.
> Expand on the deletion in Reconcile()

- cmd/apiregister-gen/generators/parser.go
- cmd/apiregister-gen/generators/unversioned_generator.go
- cmd/apiregister-gen/generators/versioned_generator.go
> Fix issue with the strategy tag not being respected.

- docs/concepts/aggregation.md
Fix typos: serveral -> several
> Fix typos: serveral -> several

- SECURITY_CONTACTS
> adding Security Contact

- cmd/apiserver-boot/boot/create/subresource.go
> [Subresource] Make the generated code working with v1.12 

- cmd/apiserver-boot/boot/create/util.go
> Chore: Revise apiserver-boot resource group flag explanation

- cmd/apiregister-gen/generators/parser.go
- cmd/apiregister-gen/generators/unversioned_generator.go
- example/.gitignore
- example/pkg/apis/innsmouth/v1/deepone_types.go
> Bugfix: Support alias on primitive types

- cmd/apiserver-boot/boot/build/generate.go
Fixes: #317 
A walkaround for finding GOROOT env var
> Bugfix: Ensure GOROOT env var on running openapi-gen

- Gopkg.toml
> Bugfix: sync dep toml version for apiserver-builder-alpha

- pkg/apiserver/apiserver.go
- pkg/cmd/server/start.go
> Feat: Insecure endpoins for healthz

- pkg/cmd/server/start.go
addresses comment [https://github.com/kubernetes-incubator/apiserver-builder-alpha/issues/252#issuecomment-487441428](https://github.com/kubernetes-incubator/apiserver-builder-alpha/issues/252#issuecomment-487441428)
Fixes: #252
> Bugfix: Set pagination option correctly via feature gate

- cmd/apiserver-boot/boot/build/build_executables.go
Signed-off-by: Xiaoxi He <xxhe@alauda.io>
> Fix 'controller-manager' binary not found

- cmd/apiserver-boot/boot/create/resource.go
- cmd/apiserver-boot/boot/create/util.go
- test/Makefile
aligning w/ kubebuilder, example
```
kimmin-mpb:example zuoxiu.jm$ apiserver-boot create resource --group kingsport --version v1 --resource matts --kind Matt
Create Resource [y/n]
y
Create Controller [y/n]
y
Create Admission Controller [y/n]
y
```
> Feat: Make create resource commands interactive

- cmd/apiserver-boot/boot/init_repo/repo.go
- example/cmd/apiserver/main.go
- pkg/cmd/server/start.go
Add support for user defined flags, for example:
apiserver --test-flag=xxx
> Add support for user defined flags

- docs/concepts/api_building_overview.md
> Chore: Fixes broken api-convention link

- pkg/cmd/server/start.go
> Bugfix: Fixes mutual log verbosity for klog/glog

- cmd/glide.lock
- cmd/glide.yaml
- cmd/vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
- cmd/vendor/k8s.io/gengo/generator/import_tracker.go
- cmd/vendor/k8s.io/gengo/generator/import_tracker_test.go
ref https://github.com/kubernetes/gengo/pull/153
> Bugfix: Upgrade gengo dependency to fix nil panic

- docs/adding_non_namespaced_resources.md
- Steps in the document are out-dated and doesn't work. 
- Updated with the steps which does work.
> Fixed doc adding_non_namespaced_resources with correct steps

- cmd/apiserver-boot/boot/create/resource.go
> Bugfix: Admission controller build failure on 1.16

- cmd/apiregister-gen/generators/package.go
- cmd/apiserver-boot/boot/build/generate.go
- cmd/go.mod
close #444 
Signed-off-by: Aylei <rayingecho@gmail.com>
> Honor --go-header-file flag in apiregistry-gen

- README.md
> Fixes broken step-by-step example link

- BUILD.bazel
- cmd/BUILD.bazel
- cmd/apiserver-boot/boot/init_repo/vendor.go
- cmd/apiserver-boot/boot/util/BUILD.bazel
- cmd/apiserver-boot/boot/util/untar.go
- cmd/apiserver-boot/boot/version/BUILD.bazel
- example/basic/BUILD.bazel
- example/basic/build-tools.sh
- test/BUILD.bazel
- test/build-tools.sh
use bazel's release packaging while testing `example/basic`. Rewrite `example/basic/build-tools.sh` by using bazel
> test: use bazel to get bins while testing

- Makefile
- scripts/print-workspace-status.sh
/cc @weixiao-huang 
PTAL, thanks
> Using bazel to run "make build"

- Makefile
- cmd/apiserver-boot/boot/init_repo/repo.go
/cc @weixiao-huang 
so that the generated repo can be working w/ bazel correctly
> Fixes repo bazel template

- cmd/apiserver-boot/boot/build/build_container.go
- cmd/apiserver-boot/boot/build/build_executables.go
> Build executables/container: opt-out apiserver/controller

- cmd/apiserver-boot/boot/build/build_resource_config.go
Apiversion should be updated for Deployment and StatefulSet resources.
> Fix apiVersions of Deployment and StatefulSet resources

- pkg/cmd/server/start.go
> fix duplicate add etcd

- docs/building_docs.md
broken link for config example
> broken link

- docs/compare_with_kubebuilder.md
broken link for api conversion
> broken link for api conversion

- docs/adding_custom_rest.md
- docs/tools_user_guide.md
Remove redundant blobs / masters from links
> Remove redundant blobs / masters from links

- Makefile
> Chore: Remove references to incubator

- cmd/apiserver-boot/boot/build/build_resource_config.go
> bugfix: fix service selector mistake

- README.md
Reverts kubernetes-sigs/apiserver-builder-alpha#628
> Revert "Doc: Adding a demo gif"

- README.md
Reverts kubernetes-sigs/apiserver-builder-alpha#629
> Revert "Revert "Doc: Adding a demo gif""
