kubernetes-sigs/apiserver-builder-alpha

cmd/apiregister-gen/generators/versioned_generator.go
pkg/builders/api_versioned_resource_builder.go

NewApiStoragelessResource actually allows you to pass in a custom storage instead of using the standard impl.
It is better to name it correctly. Also we can use the same func for API Resource with custom REST storage when needed.
/cc @pwittrock

*: rename NewApiStorageLessResource to NewApiResourceWithStorage

---

docs/concepts/README.md
docs/concepts/auth.md

This commit introduces the `docs/concepts/` directory, which we should
use for documenting concepts that users should understand about how
their API servers are working.
Currently, the only document in this directory is a discussion on how
authentication, authorization, and certificates work for an addon API
server.

[docs] Describe auth for addon API servers

---

pkg/builders/api_versioned_resource_builder.go

Reverts kubernetes-incubator/apiserver-builder#31
Reverting until vendored deps are updated

Revert "Update for compatibility with newest apiserver code"

---

cmd/apiregister-gen/generators/controller_generator.go
cmd/apiserver-boot/boot/create_resource.go
cmd/apiserver-boot/boot/init.go
cmd/apiserver-boot/boot/run.go
example/Makefile
example/cmd/controller-manager/main.go
example/pkg/controller/university/university_controller_test.go
example/pkg/controller/university/util_test.go
pkg/controller/controller.go

- Support before/after hooks on reconcile methods
- Add integration testing for example controller
- Generating meaningful tests for types when creating them from apiserver-boot

Test support for controllers

---

cmd/apiserver-boot/boot/create_resource.go
cmd/apiserver-boot/boot/glide.go
cmd/apiserver-boot/boot/init.go

- Remove unnecessary k8s.io/kubernetes dependency from glide
- Switch apiserver-boot create-resource to generate tests using ginkgo

Remove k8s.io/kubernetes dep and switch to ginkgo tests

---

cmd/apiregister-gen/generators/parser.go
cmd/apiserver-boot/boot/build.go
cmd/apiserver-boot/boot/create_resource.go
cmd/apiserver-boot/boot/create_resource_group.go
cmd/apiserver-boot/boot/create_resource_version.go
cmd/apiserver-boot/boot/docs.go
cmd/apiserver-boot/boot/generate.go
cmd/apiserver-boot/boot/glide.go
cmd/apiserver-boot/boot/init.go
cmd/apiserver-boot/boot/run.go
cmd/apiserver-boot/boot/util.go
cmd/apiserver-boot/main.go
cmd/apiserver-builder-release/main.go

This saves a surprising amount of complexity, two lines at a time.
Instead of
```go
fmt.Fprintf(os.Stderr, "GOPATH not defined\n")
os.Exit(-1)
```
write
```go
log.Fatal("GOPATH not defined")
```
@pwittrock

cmd: simplify fatal error printing

---

docs/concepts/auth.md

The steps for creating serving certificates were missing a pair of
quotes, which could have lead to some confusion.
This also clarifies the naming of the serving certs a bit: many places
refer to the cert and key as `.crt` and `.key`, but `cfssl` outputs them
as `.pem` and `-key.pem`.

docs: fix quoting issue, clarify naming in auth.md

---

cmd/apiserver-boot/boot/build.go
cmd/apiserver-boot/boot/create_resource.go
cmd/apiserver-boot/boot/create_resource_group.go
cmd/apiserver-boot/boot/create_resource_version.go
cmd/apiserver-boot/boot/init.go

- Automatically run `glide-install` with `init`
- Automatically run `generate` with `build`
- Validate that the group, version, kind are formatted correctly

Ease of use improvements for apiserver-boot

---

cmd/apiserver-boot/boot/init.go

Fixes #63
apiserver-boot init now uses the domain in the etcd path instead of hardcoding it

apiserver-boot init now uses the domain in the etcd path instead of hardcoding it

---

cmd/apiregister-gen/generators/controller_generator.go
cmd/apiserver-boot/boot/create_resource.go
cmd/apiserver-boot/boot/util.go

informer-gen generates field names for the versioned interface by
making plural forms of the names of the corresponding resource kinds.
apiregister-gen, in its turn, generates code that references these fields by
uppercased resource name form. That is, when creating a CamelCasedType resource
kind, apiregister-gen inserts calls to Camelcasedtypes(), while informer-gen
generates CamelCasedTypes() interface field name.
Fix apiregister-gen to use the same form of these names as informer-gen.

Fix informer interface usage for CamelCased resource kinds

---

cmd/apiserver-boot/boot/build.go
cmd/apiserver-boot/boot/build_container.go
cmd/apiserver-boot/boot/build_resource_config.go
cmd/apiserver-boot/boot/util.go
cmd/apiserver-boot/main.go

- change `build-container flag` --tag to --image
- fix bug in build-container where it tries to build the wrong binary
- add `build-resource-config` command to generate certs and build resource config to run container as an aggregated apiserver

Better support for aggregated apiservers

---

cmd/apiserver-boot/boot/build/build_resource_config.go
cmd/apiserver-boot/boot/build/docs.go
cmd/apiserver-boot/boot/create/resource.go
cmd/apiserver-boot/boot/run/in_cluster.go
cmd/apiserver-boot/boot/run/local.go
docs/building_docs.md
glide.lock
glide.yaml

- apiserver-boot create group version resource now creates docs/examples yamls and sample/config
- certs are now created in config/certs
- update ref-docs vendor pin

Various: Create docs examples and samples with resource.  Move where certs are generated.

---

docs/concepts/README.md
docs/concepts/aggregation.md

This commit adds an overview of how aggregation works to the concepts
directory.  It covers the basics of how discovery information is used by
kubectl, and how the aggregator serves basic discovery information and
proxies requests.

[docs] Add concepts documentation for aggregation

---

README.md

The README current points at one of the individual concepts docs (the
auth one).  It should point at the concepts readme, which has a list of
all the concepts docs (that way, we don't have to maintain a list in two
seperate places).

[docs] Point README at concepts index

---

cmd/apiregister-gen/generators/versioned_generator.go
pkg/builders/api_versioned_resource_builder.go

ApiVersion variable from the versioned package is initialized both
in the apiserver and in the controller-manager because they both
import the versioned package.
When a custom REST handler is defined, its NewFooREST() constructor is
being called directly during ApiVersion initialization. This constructor
may contain some other logic besides simply initializing the custom REST
registry type. For example it may establish a connection to some service.
And we'll end up with an extra unused connection to the external
service, established from the controller manager.
Passing NewFooREST as a function value to builders.NewApiResourceWithStorage()
and then calling it from versionedResourceBuilder.registerEndpoints()
solves this problem.
Fixes #92.

Do not initialize custom REST handler during ApiVersion initialization

---

cmd/apiserver-boot/boot/build/docs.go
cmd/apiserver-boot/boot/build/generate.go
cmd/apiserver-boot/boot/create/create.go
cmd/apiserver-boot/boot/init_repo/repo.go

- Clean up intermediate files after generating docs
- Support both k8s.io/client-go and k8s.io/api types when generating openapi
- Allow copyright file to be specified in a flag

Better support for non-apiserver-builder repos

---

.travis.yml
cmd/apiserver-boot/boot/create/resource.go
test/Makefile
test/boilerplate.go.txt
test/build-tools.sh
test/travis.sh

This test does these action:
* build an apserver-boot tarball
* genereate a test api server with namespaces and non-namespaced
resources.
* run tests for this api server

travis: add a new test case to create a test api server from scratch

---

pkg/cmd/server/start.go

A new flag, '--loglevel' is added on the API Server's command line, so that users can use this flag to specify glog's output level directly.

Allow specifying glog's output level on command line

---

cmd/apiregister-gen/generators/controller_generator.go
cmd/apiserver-boot/boot/create/resource.go
example/pkg/controller/festival/controller.go
example/pkg/controller/university/university_controller.go
pkg/builders/default_controller_fns.go

So that users can put additional running logic in this function.

Add Run function to controller's implementation

---

pkg/cmd/server/start.go

Register functions must be set-up before they're called.

Fix kubernetes gvk initialization order

---

docs/concepts/aggregation.md
docs/concepts/auth.md

This adds some basic concepts information on RBAC to the auth concepts documentation.  It just mentions the two roles needs to allow delegated authentication and authorization.  The main Kubernetes documentation already has good documentation on the general usage of RBAC, although we may want a section eventually on crafting "bootstrap policy" for your API server.

[docs] Add Concepts info on RBAC

---

cmd/apiserver-boot/boot/build/build_resource_config.go
docs/running_in_cluster.md

Currently I'm unable to generate and deploy api server with just one command, because I'm using secured private docker registry and k8s cluster with RBAC enabled.
What solves problem for me is editing apiserver.yaml and adding `ImagePullSecrets` and `ServiceAccount` to apiserver deployment. But doing this manually is cumbersome.
I would like to run it on one command like this (and this pull request enables it):
```bash
apiserver-boot run in-cluster --name group_name --namespace default --image private_repo/IMAGE --image-pull-secrets private_repo_secret --service-account service_account_with_rights
```
Currently I need to run:
```bash
apiserver-boot build container --image $IMAGE_NAME
docker push $IMAGE_NAME
rm config/apiserver.yaml
apiserver-boot build config --name remoteenvsgroup …
```

Additional fields for apiserver.yam (imagePullSecrets and serviceAccount)

---

cmd/apiserver-boot/boot/build/build_resource_config.go

fixed https://github.com/kubernetes-incubator/apiserver-builder/issues/186

avoid errors in "openssl req" command for old openssl versions.

---

cmd/apiserver-boot/boot/run/local_aggregated.go

cmd/apiserver-boot: do not use authentication-skip-lookup

---

docs/concepts/api_building_overview.md

Fix a typo:
Line 273/279: overriden->overridden

Fix typos in api_building_overview.md

---

cmd/apiserver-boot/boot/build/build_executables.go
cmd/apiserver-boot/boot/build/generate.go

Syncing up w/ k/k, internal client (including clientset/informer/lister) is being removed so we dont generate this anymore.
Note that internal types should only be used in their REST storage or HTTP handlers which is completely transparent for external system users.

Deprecate internal client/informer/lister generation

---

docs/adding_subresources.md

will update the naming once #308 gets in. 
scale is an exception that it should always use `autoscaling.Scale` as its kind

Chore: Revise subresource docs: avoid scale as example

---

pkg/controller/controller.go

From my condition, I need a queue worker to retry one sentence when error happens any way. The controller generated by `apiserver-builder` cannot meet the expectation. But it seems it is very easy to add this feature!

QueueWorker can work with infinite retry

---

cmd/apiregister-gen/generators/parser.go
cmd/apiregister-gen/generators/unversioned_generator.go
cmd/apiregister-gen/generators/versioned_generator.go
cmd/apiserver-boot/boot/create/subresource.go
example/pkg/apis/miskatonic/v1beta1/computer_student_types.go
example/pkg/apis/miskatonic/v1beta1/computer_student_types_test.go
example/pkg/apis/miskatonic/v1beta1/student_types.go
example/pkg/apis/miskatonic/v1beta1/university_types.go

Fixes: #311
now, we can add a `rest=XXX` resource tag on parent resource to support customizing REST for its subresources. additionally, a `kind=XXX` resource tag is ensured when generated.

Feat: Support customizing REST for subresource

---

cmd/apiregister-gen/generators/versioned_generator.go
example/pkg/apis/miskatonic/student.go
example/pkg/apis/miskatonic/student_computer.go
example/pkg/apis/miskatonic/v1beta1/computer_student_types.go
example/pkg/apis/miskatonic/v1beta1/student_types.go
pkg/builders/api_versioned_resource_builder.go

1. Add generic options getter to the parameter list of custom rest func so that users can easily instantiate their own store object.
2. Move REST logic to internal packages

Feat: Plumb generic options to new custom rest constructor

---

cmd/apiregister-gen/generators/admission_generator.go
cmd/apiregister-gen/generators/package.go
cmd/apiserver-boot/boot/create/resource.go
example/cmd/apiserver/main.go
example/plugin/admission/deepone/admission.go
example/plugin/admission/festival/admission.go
example/plugin/admission/initializer.go
pkg/apiserver/apiserver.go
pkg/cmd/server/admission.go
pkg/cmd/server/start.go

a dummy admission controller will be generated when specifying `--admission-controller` in the `apiserver-boot create resource` commands.

Feat: Support built-in admission controller for aggregated resource

---

cmd/apiregister-gen/generators/parser.go
cmd/apiregister-gen/generators/unversioned_generator.go
example/pkg/apis/kingsport/v1/festival_types.go
pkg/builders/api_unversioned_resource_builder.go
pkg/builders/api_versioned_resource_builder.go
pkg/builders/shortcut_storage_wrapper.go

Now we can use the resource tag `// +resource: shortname=foo` to add short-name for resource
TODO: add `--short-name` flag for resource creation commands

Feat: Support short name provider

---

pkg/cmd/server/start.go

I notice wrong golang struct coping causes OpenAPIConfig not working, so I fixed it. see #380

make OpenAPIConfig works

---

cmd/apiserver-boot/boot/create/create.go
cmd/apiserver-boot/boot/create/resource.go
cmd/apiserver-boot/boot/create/subresource.go
cmd/apiserver-boot/main.go

fix invalid resource version in example:
```
apiserver-boot create group version resource --group insect --version v1beta --kind Bee
2019/08/01 13:33:54 --version has bad format. must match ^v\d+(alpha\d+|beta\d+)*$.  e.g. v1alpha1,v1beta1,v1 but was (v1beta)
```

fix invalid resource version in example

---

cmd/apiserver-boot/boot/run/local.go
cmd/apiserver-boot/boot/run/local_aggregated.go
cmd/apiserver-boot/boot/util/util.go

Address outstanding code-review feedback from #255

Quit all processes when "apiserver-boot run local" failed 

---

pkg/builders/api_version_builder.go

in 1.12+ generator, we have typo from the field `ApiVersion#SchemaBuilder`, and we renamed it to `SchemeBuilder` in 1.15+ to align w/ k/k upstream. we preserve the old name to avoid breaking compatibility between (1.12+ generator) and (1.15+ vendor)

Chore: Compatibility for exported typo from 1.12+ generator

---

cmd/apiregister-gen/generators/parser.go

so that generated files won't twiddle

Bugfix: Sort structs by names in apiregister-gen

---

cmd/apiserver-boot/boot/create/resource.go
cmd/apiserver-boot/boot/create/util.go

add --short-name flag for resource creation commands

---

cmd/apiregister-gen/generators/versioned_generator.go
cmd/apiserver-boot/boot/create/resource.go
example/basic/Makefile
test/Makefile

close #435 
Also, `go vet` check is added in the test.
Signed-off-by: Aylei <rayingecho@gmail.com>

Fix go vet error 'composite literal uses unkeyed fields' in generated code

---

cmd/apiserver-boot/boot/init_repo/repo.go

and this will make the integration test cover the admission portion

Enable admission installation by default on repo-init

---

cmd/apiregister-gen/generators/apis_generator.go

Signed-off-by: Aylei <rayingecho@gmail.com>
Add comment for blank imports generated by `apiserver-gen`, e.g.
```go
import (
"k8s.io/apimachinery/pkg/runtime"
"sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/innsmouth"
_ "sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/innsmouth/install" // Install the innsmouth group
innsmouthv1 "sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/innsmouth/v1"
"sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/kingsport"
_ "sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/kingsport/install" // Install the kingsport group
kingsportv1 "sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/kingsport/v1"
"sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/miskatonic"
_ …
```

apiserver-gen: add comment for blank imports

---

pkg/test/suite/aggregation.go

In some circumstance, we do not need to use `gexec.Build("../../../cmd/apiserver/main.go")`, for example:
- If out apiserver dir name is not `apiserver`, like `my-apiserver`, we could not use `StartLocalAggregatedAPIServer` for test.
- While we using Bazel in our project, `gexec.Build` seems not work in Bazel
Like k8s.io/controller-runtime, we can use environment to set test asset bin path without writing hardcode things to build the local apiserver bin, for k8s.io/controller also [have similar environments](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/envtest/server.go#L50) to ensure a better extension.

feat: add envLocalAPIServerBin for avoiding building existed user-customize apiserver

---

cmd/apiregister-gen/generators/apis_generator.go

`cmd/apiregister-gen` use `k8s.io/gengo`, which will use `golang.org/x/tools/imports` for post-processing after code generation. Since apis_generator.go haven't explicitly declared `k8s.io/apimachinery/pkg/runtime` but it use `runtime` in `APIsTemplate`, `gengo` won't find import path for `runtime` and this will be done by `golang.org/x/tools/imports`. However, `goimports` cannot parse soft link. It means, if all go files in `k8s.io/apimachinery/pkg/runtime` are symlink files and point to another directory not in GOPATH, `goimports` cannot find import package for `runtime`.
An example for this is to use bazel for code generation by using `apiregister-gen`. In [k8s.io/repo-infra](https://github.com/kubernetes/repo-infra/blob/v0.0.1-alpha.1/defs/go.bzl#L104), it defines a `go_genrule` for …

fix(apiserver-gen): explicit decalre 'k8s.io/apimachinery/pkg/runtime' for apis_generator to avoid goimports bug

---

cmd/go.mod
cmd/go.sum

This 'replace' line make go build not work in go modules mod. It will cause an error below:
```
go: k8s.io/klog@v0.3.1 used for two different module paths (github.com/golang/glog and k8s.io/klog)
```
Since `github.com/golang/glog` is only referred from vendor, using go modules will discard `vendor` so that this `replace` is unnecessary.
So removing this line can avoid this error and make go modules work while building `apiserver-boot`, `apiregister-gen` and `apiserver-builder-release`

fix: remove replace of glog to klog in go.mod

---

BUILD.bazel
WORKSPACE
cmd/apiregister-gen/BUILD.bazel
cmd/apiregister-gen/generators/BUILD.bazel
cmd/apiserver-boot/BUILD.bazel
cmd/apiserver-boot/boot/build/BUILD.bazel
cmd/apiserver-boot/boot/create/BUILD.bazel
cmd/apiserver-boot/boot/init_repo/BUILD.bazel
cmd/apiserver-boot/boot/run/BUILD.bazel
cmd/apiserver-boot/boot/update/BUILD.bazel
cmd/apiserver-boot/boot/util/BUILD.bazel
cmd/apiserver-boot/boot/version/BUILD.bazel
cmd/apiserver-builder-release/BUILD.bazel
load.bzl
repos.bzl

Make bazel work for `cmd/{apiserver-boot,apiserver-builder-alpha,apiregister-gen}`. Please use bazel version at least 0.29.1. By using
```bash
bazel build cmd/apiserver-boot cmd/apiregister-gen cmd/apiserver-builder-release
```
you can build all cmd binaries by bazel.
`go_repositories` in `repos.bzl` was generated by `gazelle update-repos` from `cmd/go.mod`. This can make compile results match results of go modules in cmd/go.mod while compiling cmd binaries by bazel. The command for doing this generation is
```bash
bazel run //:gazelle -- update-repos --from_file=$PWD/cmd/go.mod --to_macro=repos.bzl%go_repositories --build_file_generation=on --build_file_proto_mode=disable --prune
```
And these modified `BUILD.bazel` was generated by using `gazelle`. The command for doing this generation …

build: upgrade bazel and rules_go version and make bazel work for cmd binaries

---

.bazelrc
cmd/apiserver-boot/boot/version/BUILD.bazel
cmd/apiserver-boot/boot/version/version.go
scripts/print-workspace-status.sh

`apiserver-builder-release` define `apiserverBuilderVersion`, `kubernetesVendorVersion`, `gitCommit`, `buildDate`, `goos`, `goarch` for `apiserver-boot`. But these variables can be defined elegantly by [rules_go's stamp variables](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#defines-and-stamping).
Also I think the default value of `goos`, `goarch` should be `runtime.GOOS` and `runtime.GOARCH`.
Using the strategy of stamp variables of bazel, after executing bazel build for `apiserver-boot`, variables in `scripts/print-workspace-status.sh` can be injected into `cmd/apiserver-boot/boot/version/version.go`.

build: add stamp variables injection for defining apiserver-builder version

---

cmd/apiserver-boot/boot/create/resource.go
example/basic/pkg/apis/innsmouth/v1/v1_suite_test.go
example/basic/pkg/apis/kingsport/v1/v1_suite_test.go
example/basic/pkg/apis/miskatonic/v1beta1/v1beta1_suite_test.go
example/basic/pkg/apis/olympus/v1beta1/v1beta1_suite_test.go
example/kine/pkg/apis/sqlite/v1alpha1/v1alpha1_suite_test.go
example/podexec/pkg/apis/podexec/v1/v1_suite_test.go
example/podlogs/pkg/apis/podlogs/v1/v1_suite_test.go
pkg/test/server.go

Sometimes, we will add `FlagConfigFuncs` in customize apiserver's `StartOptions`. This will be blocked while using `pkg/test` package since there's no `StartOptions` being registered in the `TestEnvironment`. Also, if we want to control flags of apiserver, we need to have access permission of the test apiserver's cobra command.
Moreover, lots of operations in the `Start` function of `TestEnvironment` seem to do a initialization. I think they should be moved into `NewTestEnvironment` so that we can export the `ApiserverCobraCmd` and `ApiserverOptions` to user to customize their test logic.

feat(test): move logic from Start to New for exporting apiserver cmd and options

---

cmd/apiserver-boot/boot/build/build_executables.go

Overridable CGO options for `build executables' commands

---

pkg/test/server.go

Started etcd requires a /tmp directory which doesn't exist on Windows machines. If a windows machine attempts to create a TestEnvironment, the etcd data will be saved to the relative path ./ and it will be removed when the test completes.

Test env windows support
